on: push
name: Flutter Test
jobs:
  build:
    name: Run Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - run: flutter test


    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    # install packages needed
    - name: install required packages
      run: Rscript -e 'install.packages(c("rmarkdown","gratia"))'

    # Render READEME.md using rmarkdown
    - name: render README
      run: Rscript -e 'rmarkdown::render("Readme.Rmd", output_format = "md_document")'

    - name: commit rendered README
      run: |
        git config --global user.email "kkapoor3@uh.edu"
        git config --global user.name "Kartik Kapoor"
        git add Readme.md 
        git show-ref
        git commit -m "Re-build Readme.md" || echo "No changes to commit"
        git push origin main || echo "No changes to commit"